{{- if eq (include "redis.deploy" .) "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-redis-config" (include "airsgateway.fullname" .) }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
data:
  redis.conf: |
    dir /data
    appendonly yes
    protected-mode yes
{{- with .Values.redis.config.extra }}
{{ . | indent 4 }}
{{- end }}
{{- end }}
