{{- if eq (include "redis.deploy" .) "true" }}
{{- if and .Values.redis.auth.enabled .Values.redis.auth.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.secretName" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.redis.auth.existingSecretPasswordKey }}: {{ .Values.redis.auth.password | b64enc | quote }}
{{- end }}
{{- end }}
